# Generated by Django 5.1.1 on 2024-09-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductEntry',
        ),
    ]
