# Generated by Django 5.1.1 on 2024-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
